config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  get "home/about"=>"homes#about"
  root :to =>"homes#top"
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]do
    get "search", to: "users#search"
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment,presence:true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    book_comment = current_user.book_comments.new(book_comment_params)
    book_comment.book_id = @book.id
    book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/views/book_comments/_book_comment.html.erb
<table>
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td>
      <%= book_comment.comment %>
    </td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true %>
      <% end %>
    </td>
<% end %>
  </tr>
</table>

app/views/book_comments/create.js.erb
 $("#book_comment").html("<%= j(render 'book_comments/book_comment', book: @book) %>");
 $("textarea").val('')

app/views/book_comments/destroy.js.erb
 $("#book_comment").html("<%= j(render 'book_comments/book_comment', book: @book) %>");